CREATE DATABASE IF NOT EXISTS BlueSchool;

CREATE TABLE IF NOT EXISTS Niveis_Acessos (
  ID INT(11) NOT NULL AUTO_INCREMENT,
  NOME VARCHAR(50) NOT NULL,
  CREATED datetime NOT NULL,
  MODIFIED datetime DEFAULT NULL,
  PRIMARY KEY (ID)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=4 ;

INSERT INTO Niveis_Acessos (ID, NOME,CREATED,MODIFIED) VALUES
(1, 'Gestor', '2021-30-8 00:00:00', NULL),
(2, 'Colaborador', '2021-30-8 00:00:00', NULL),
(3, 'Professor', '2021-30-8 00:00:00', NULL);
(4, 'Aluno', '2021-30-8 00:00:00', NULL);

CREATE TABLE IF NOT EXISTS Gestor(
ID INT(11) NOT NULL AUTO_INCREMENT,
NOME VARCHAR(50) NOT NULL,
SITUACAO_ID int(11) NOT NULL DEFAULT '0',
NIVEL_DE_ACESSO INT(11) NOT NULL,
EMAIL VARCHAR(50) NOT NULL,
SENHA VARCHAR(11) NOT NULL,
PRIMARY KEY (ID)
)ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=11 ;

INSERT INTO Gestor(ID,NOME,SITUACAO_ID,NIVEL_DE_ACESSO,EMAIL,SENHA) VALUES
(NULL,'Matheus Henrique Ribeiro Diamantino',1,1,'matheus.henrique@blueschool.com.br','gestor@blue');

CREATE TABLE IF NOT EXISTS Colaborador (
ID INT NOT NULL AUTO_INCREMENT,
NOME VARCHAR(50) NOT NULL,
GENERO VARCHAR(50) NOT NULL,
NASCIMENTO DATE NOT NULL,
CPF VARCHAR(15) NOT NULL,
RG VARCHAR(15) NOT NULL,
ESTADO VARCHAR(50) NOT NULL,
CIDADE VARCHAR(50) NOT NULL,
ENDERECO VARCHAR(100) NOT NULL,
CEP VARCHAR(15) NOT NULL,
DEPARTAMENTO VARCHAR(50) NOT NULL,
CARGO VARCHAR(50) NOT NULL,
JORNADA VARCHAR(50) NOT NULL,
SALARIO VARCHAR(15) NOT NULL,
EMAIL VARCHAR(50) NOT NULL,
SENHA VARCHAR(50) NOT NULL,
TELEFONE VARCHAR(16) NOT NULL,
SITUACAO INT(11) NOT NULL,
NIVEL INT(11) NOT NULL, 
PRIMARY KEY(ID)
)ENGINE=InnoDB  DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS Projeto (
ID INT NOT NULL AUTO_INCREMENT ,
NOME VARCHAR(50) NOT NULL,
DESCRICAO VARCHAR(100) NOT NULL,
DEPARTAMENTO VARCHAR(50) NOT NULL,
UNIDADE VARCHAR(100) NOT NULL,
SOLICITANTE VARCHAR(100) NOT NULL,
DIA DATE NOT NULL,
JUSTIFICATIVAS VARCHAR(3000) NOT NULL,
OBJETIVO VARCHAR(3000) NOT NULL,
BENEFICIOS VARCHAR(3000) NOT NULL,
RESTRICOES VARCHAR(3000) NOT NULL,
REQUISITOS VARCHAR (3000) NOT NULL,
ENTREGAVEIS VARCHAR(3000) NOT NULL,
RISCOS VARCHAR(3000) NOT NULL,
RESPONSAVEIS VARCHAR(3000) NOT NULL,
EQUIPE VARCHAR(3000) NOT NULL,
PARCERIAS VARCHAR(3000) NOT NULL,
PRAZOS VARCHAR(3000) NOT NULL,
CUSTOS VARCHAR(3000) NOT NULL,
PRIMARY KEY(ID)
)ENGINE=InnoDB  DEFAULT CHARSET=latin1;